baseurl = "https://artonson.github.io/"
languageCode = "en-us"
title = "Alexey Artemov"
## theme = "hugo-xmin-art"
paginate = 2
Copyright = "© Yuanyuan GE 2020"
canonifyurls = true

[params]
description = "Enter your personal description"
authorlocation = "authorlocation"
cover = "images/cover.png"
## save the image you want to use as background picture in directory "./static/images"author = "author name"(delete this line when editing)
logo = "images/logo.png"
## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)
githubName = "your github name"
linkedinName = "your linkedin name"
email = "your email"
instagramName = "your ins name"
hideHUGOSupport = false
footer =  "&copy; [Alexey Artemov](https://artonson.github.io) 2021&ndash;2024 | [Email](mailto:artonson@yandex.ru) | [Github](https://github.com/artonson) | [Scholar](https://scholar.google.ru/citations?user=5lVsH-IAAAAJ&hl=en) | [YouTube](https://www.youtube.com/channel/UCO946RPg2Yp2PXFzon9_73g) | [LinkedIn](https://www.linkedin.com/in/artonson/) | [Twitter](https://twitter.com/artonson) | [Telegram](https://t.me/research_meets_art)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[markup.goldmark.parser.attribute]
    block = true
    title = true

[[menu.main]]  # here are the buttons on the menu
name = "Home" # Button will display as "Home"
weight = 1 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "CV"
weight = 2
identifier = "cv"
pre = "<br />"
url = "/cv_alexey_artemov.pdf"

[[menu.main]]
name = "Research"
weight = 3
identifier = "publications"
pre = "<br />"
url = "/publications"

[[menu.main]]
name = "Education"
identifier = "teaching"
pre = "<br />"
url = "/teaching"
weight = 4

#[[menu.main]]
#name = "Students"
#identifier = "students"
#pre = "<br />"
#url = "/students"
#weight = 5

#[[menu.main]]
#name = "Code & Resources"
#identifier = "code_resources"
#pre = "<br />"
#url = "/code_resources"
#weight = 6

[[menu.main]]
name = "Art & Heritage"
identifier = "art_heritage"
pre = "<br />"
url = "/art"
weight = 6

#[[menu.main]]
#name = "Press"
#identifier = "press"
#pre = "<br />"
#url = "/press"
#weight = 7


[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
